### ISSUE TITLE
Running Snikket behind nginx-proxy-letsencrypt

### ISSUE THREAD

**Issue by mat-l** [snikket-im/snikket-server#8]
Dear all,
first of all thank you for your work and this new project :)

I am having some trouble with the set up in my docker environment. I guess it could be a combination with the "nginx-proxy-letsencrypt" container for providing SSL certificates.

For the basic set up I followed the quick-start instructions over here https://snikket.org/service/quickstart/. I extended it environmental variable with the parameters VIRTUAL_HOST=tld, LETSENCRYPT_HOST=tld and the VIRUTAL_PORT=8083. In the set up I cannot just use the ports 80 and 443 case they are used by the nginx-proxy-letsencrypt container for providing SSL certificates to other containers as well.

After deploying the container and generating a invite links with "sudo docker exec snikket create-invite --admin" I am able to ob the link in a browser with a valid SSL certificate. Opening the invitation with the snikket Android App I cannot create the account and/or login. The message is "TLS-handling error".

The logs from the container are not helping me that much:
2020-06-05T08:33:05.938526444Z c2s563a12a8a4b0                     info	Client connected
2020-06-05T08:33:05.960633897Z c2s563a12a8a4b0                     info	Client disconnected: no shared cipher,

In my firewall I have opened the ports as mentioned here: https://github.com/snikket-im/snikket-server/blob/master/docs/advanced/firewall.md

docker-compose:
```
version: "3.3"

services:
  snikket:
    container_name: snikket
    image: snikket/snikket:alpha
    ports:
      - 5222:5222
      - 5269:5269
      - 5000:5000
      - 3478:3478
      - 3479:3479
      - 5349:5349
      - 5350:5350
      - 49152:49152
      - 8083:80
      - 5080:80
      - 5443:443
    env_file: snikket.conf
    restart: unless-stopped
    network_mode: host
    volumes:
      - snikket_data:/snikket
    network_mode: hostingnetwork
    hostname: snikketcontainer

volumes:
  snikket_data:
```

snikket.conf
```
# The primary domain of your Snikket instance
SNIKKET_DOMAIN=tld

# An email address where the admin can be contacted
# (also used to register your Let's Encrypt account to obtain certificates)
SNIKKET_ADMIN_EMAIL=user@tld

VIRTUAL_HOST=tld
LETSENCRYPT_HOST=tld
VIRUTAL_PORT=8083

SNIKKET_TWEAK_HTTP_PORT=5080
SNIKKET_TWEAK_HTTPS_PORT=5443
```

Could you please help me with my setup?
Best regards
